name: "Test Scripts"

on:
  pull_request_target:
    types: [opened, synchronize]
    paths:
      - 'vci-issuers*.json'
      - 'scripts/*.py'
      - '.github/workflows/test-scripts.yaml'

jobs:
  runTests:
    name: "Test Scripts"
    runs-on: [ubuntu-latest]
    steps:
      - name: "Debugging Workflow"
        run: 'echo "Empty Workflow Test"'
          
#       - uses: actions/checkout@v4
#         with:
#           ref: ${{ github.event.pull_request.head.sha }}
#           path: 'head'
# 
#      - uses: actions/checkout@v4
#        with:
#          ref: ${{ github.event.pull_request.base.sha }}
#          path: 'base'
# 
#       - name: Cache Python venv
#         uses: actions/cache@v4
#         with:
#           path: venv
#           key: ${{ runner.os }}-build-${{ hashFiles('head/scripts/requirements.txt') }}
# 
#       - name: "Run tests"
#         if: ${{ hashFiles('head/scripts') != hashFiles('base/scripts') }}
#         run: |
#           python -m venv venv
#           source venv/bin/activate
#           pip install -r head/scripts/requirements.txt
#           cd head/scripts
#           python -m unittest test.common_test