name: "Validate on push (Pass)"

on:
  pull_request_target:
    types: [opened, synchronize]
    paths-ignore:
      - 'vci-issuers*.json'
      - 'scripts/*.py'
      - '.github/workflows/validate-issuers.yaml'
  push:
    branches:
      - main
    paths-ignore:
      - 'vci-issuers*.json'
      - 'scripts/*.py'
      - '.github/workflows/validate-issuers.yaml'
  workflow_call:
    inputs:
      ref:
        required: true
        type: string

jobs:
  runTests:
    name: "Validate Issuers File"
    runs-on: [ubuntu-latest]
    steps:
      - run: 'echo "No build required" '